# Generated by Django 5.1.4 on 2025-02-17 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_omeglechatuser'),
    ]

    operations = [
    ]
