# Generated by Django 5.1.4 on 2025-02-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20250217_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='omeglechatuser',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='omeglechatuser',
            name='user_id',
            field=models.CharField(default='a', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='omeglechatuser',
            name='username',
            field=models.CharField(default='a', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='omeglechatuser',
            name='age',
            field=models.IntegerField(),
        ),
    ]
