# Generated by Django 5.1.4 on 2025-02-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_omeglechatuser_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omeglechatuser',
            name='user_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='omeglechatuser',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
