# Generated by Django 5.1.4 on 2025-01-06 09:51

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultuser',
            name='image_url',
            field=models.ImageField(default='images/default.png', upload_to='images', validators=[users.validators.max_size_validator]),
        ),
    ]
