# Generated by Django 5.1.4 on 2025-01-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_defaultuser_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultuser',
            name='age',
        ),
        migrations.AddField(
            model_name='defaultuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
