# Generated by Django 5.1.4 on 2025-01-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_defaultuser_age_defaultuser_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultuser',
            name='is_online',
            field=models.CharField(choices=[('O', 'ONLINE'), ('F', 'OFFLINE'), ('I', 'IDLE')], default='F', max_length=1),
        ),
    ]
