# Generated by Django 5.1.4 on 2025-01-12 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_defaultuser_is_online'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defaultuser',
            old_name='status',
            new_name='status',
        ),
    ]
