# Generated by Django 5.1.4 on 2025-02-17 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_omeglechatuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OmegleChatUser',
        ),
    ]
