# Generated by Django 4.2.20 on 2025-04-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_delete_omeglechatuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultuser',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10),
        ),
    ]
