# Generated by Django 4.2.20 on 2025-05-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profilelike_profileview'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultuser',
            name='image_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
