# Generated by Django 4.2.20 on 2025-08-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_defaultuser_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultuser',
            name='boundary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='defaultuser',
            name='causes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='defaultuser',
            name='favorite_thing',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='defaultuser',
            name='is_discoverable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='defaultuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='defaultuser',
            name='looking_for',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='defaultuser',
            name='specs',
            field=models.JSONField(default=list),
        ),
    ]
