# Generated by Django 4.2.20 on 2025-08-11 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_defaultuser_boundary_defaultuser_causes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultuser',
            name='image_link',
        ),
        migrations.RemoveField(
            model_name='defaultuser',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='defaultuser',
            name='snapchat',
        ),
        migrations.RemoveField(
            model_name='defaultuser',
            name='tiktok',
        ),
        migrations.AddField(
            model_name='defaultuser',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='blocked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='defaultuser',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defaultuser',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defaultuser',
            name='reported_fake',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='defaultuser',
            name='sexual_orientation',
            field=models.CharField(choices=[('male', 'Interested in Males'), ('female', 'Interested in Females'), ('bisexual', 'Bisexual')], default='bisexual', max_length=10),
        ),
        migrations.AlterField(
            model_name='defaultuser',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='defaultuser',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='defaultuser',
            name='image_url',
            field=models.ImageField(default='images/default.png', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='defaultuser',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='defaultuser',
            name='status',
            field=models.CharField(choices=[('O', 'ONLINE'), ('F', 'OFFLINE'), ('I', 'IDLE'), ('C', 'CHAT')], default='F', max_length=1),
        ),
        migrations.CreateModel(
            name='UserPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_pictures')),
                ('is_profile_picture', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
