# Generated by Django 4.2.20 on 2025-08-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_defaultuser_image_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultuser',
            name='image_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
