# Generated by Django 4.2.20 on 2025-08-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_defaultuser_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultuser',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='defaultuser',
            name='snapchat',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='defaultuser',
            name='tiktok',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
