# Generated by Django 4.2.20 on 2025-08-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_defaultuser_instagram_defaultuser_snapchat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultuser',
            name='specs',
            field=models.JSONField(default={'drink': '', 'height': '', 'religion': '', 'smoke': ''}),
        ),
    ]
