# Generated by Django 4.2.20 on 2025-08-13 14:43

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_defaultuser_specs'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultuser',
            name='image_2',
            field=models.ImageField(default='images/default.png', upload_to='images', validators=[users.validators.max_size_validator]),
        ),
        migrations.AddField(
            model_name='defaultuser',
            name='image_3',
            field=models.ImageField(default='images/default.png', upload_to='images', validators=[users.validators.max_size_validator]),
        ),
        migrations.AddField(
            model_name='defaultuser',
            name='image_4',
            field=models.ImageField(default='images/default.png', upload_to='images', validators=[users.validators.max_size_validator]),
        ),
        migrations.AddField(
            model_name='defaultuser',
            name='image_5',
            field=models.ImageField(default='images/default.png', upload_to='images', validators=[users.validators.max_size_validator]),
        ),
        migrations.AddField(
            model_name='defaultuser',
            name='image_profile',
            field=models.ImageField(default='images/default.png', upload_to='images', validators=[users.validators.max_size_validator]),
        ),
        migrations.DeleteModel(
            name='UserPicture',
        ),
    ]
